### ISSUE TITLE
The page with CV open with error 404

### ISSUE THREAD

**Issue by alekseipiatkovskii** [Awilum/awilum.dev#11]
BUG
![Снимок экрана (385)](https://user-images.githubusercontent.com/118691133/210138526-31d526f7-5bcf-4729-994a-d6999b519288.png)

Description:
The file is not detected on the page https://awilum.github.io/sergey-romanenko-cv.pdf

Environment:
HP Laptop 15s-eq1314ur,Windows 10 Версия 22H2 Сборка 19045.2364 Тип х64
Chrome. Google Chrome 108.0.0.0 (WebKit 537.36)

Steps to reproduce:

1.Open the page https://awilum.github.io/about/
2.Click on the link “DOWNLOAD CV”

Actual result:
Page https://awilum.github.io/sergey-romanenko-cv.pdf is opened with error 404 File not found

Expected Result:
Page https://awilum.github.io/sergey-romanenko-cv.pdf with CV is open

**Comment by Awilum** [comment]
@alekseipiatkovskii I decide to remove link for sergey-romanenko-cv.pdf from about page for now.

Please close this ticket.
