### ISSUE TITLE
The photo disappears when the page width is reduced below 1024

### ISSUE THREAD

**Issue by alekseipiatkovskii** [Awilum/awilum.dev#14]
Documentation

Description:
The photo disappears when on https://awilum.github.io/ and https://awilum.github.io/about/ the page width is reduced below 1024

Environment:
HP Laptop 15s-eq1314ur,Windows 10 Version 22H2 Build 19045.2364 Тип х64
Chrome. Google Chrome 108.0.0.0 (WebKit 537.36)

Steps to reproduce:

1.Open the page https://awilum.github.io/
2. Set the page width to 1024
3. Set the page width to 1023
4 .Open the page https://awilum.github.io/about/
5.Set the page width to 1024
6. Set the page width to 1023

Actual result:
![Снимок экрана (389)](https://user-images.githubusercontent.com/118691133/210140369-446cce2a-0e1c-4661-9eb2-aebec6d442f1.png)
![Снимок экрана (388)](https://user-images.githubusercontent.com/118691133/210140371-bf5cc744-7d0e-4db9-aa32-fbdf12225644.png)
![Снимок экрана (387)](https://user-images.githubusercontent.com/118691133/210140372-d2b69512-c3ae-4ae1-a5bb-5f6d7b58fadf.png)
![Снимок экрана (386)](https://user-images.githubusercontent.com/118691133/210140373-428522f3-9349-45aa-b4c0-08f005262452.png)
After the third and sixth steps there is a photo

Expected Result:
Photo disappears

**Comment by Awilum** [comment]
Issue fixed. Updates on Live.

@alekseipiatkovskii  please retest

**Comment by alekseipiatkovskii** [comment]
Retest is done, the issue is fixed.
