### ISSUE TITLE
External link open in the current tab

### ISSUE THREAD

**Issue by alekseipiatkovskii** [Awilum/awilum.dev#16]
Bug

Description:
On the main page when clicking on the external link [[GITHUB]](https://github.com/Awilum), the page open on the current tab

Environment:
HP Laptop 15s-eq1314ur,Windows 10 Версия 22H2 Сборка 19045.2364 Тип х64
Chrome. Google Chrome 108.0.0.0 (WebKit 537.36)

Steps to reproduce:

1. Open page https://awilum.github.io
2. Click on any link[[GITHUB]](https://github.com/Awilum)

Actual result:
The page open in a current tab

Expected Result:
The page opens in a new tab

https://user-images.githubusercontent.com/118691133/210370876-a18476cb-c414-4e1c-89d7-9860f6231fee.mp4

**Comment by Awilum** [comment]
Issue fixed. Updates on Live.

@alekseipiatkovskii please retest

**Comment by alekseipiatkovskii** [comment]
Retest is done, the issue is fixed.
