### ISSUE TITLE
404 File not found on click on “Documentation” title

### ISSUE THREAD

**Issue by meowlder** [Awilum/awilum.dev#21]
Description:
“Documentation” title does not forward to the documentation page

Environment: 
Chrome 108.0.5359.98, 1920x1080; MacOS 12.6

Steps to reproduce: 
1. Open the page https://awilum.github.io/thermage/
2. Click on the “Documentation” button in the menu bar
3. Click on  the “Documentation” title under the menu bar

Actual result: 
“Documentation” title goes to "404 File not found" on click

Expected result:
“Documentation” title goes to the documentation page on click

Attachment: 

https://user-images.githubusercontent.com/121216123/210541499-fad70959-b453-4dc4-8294-f290deac24c3.mov

**Comment by Awilum** [comment]
Issue fixed. Updates on Live.

@vetamalder please retest

**Comment by meowlder** [comment]
Retest is done. May i add an improvement? I don't think the title needs to forward to itself, because there is already a redirect to "Documentation" from the menu bar, and the title does not do this on the "Thermage" page.

**Comment by Awilum** [comment]
@vetamalder please create a new ticket with your suggestions on this topic. 

Current issue may be closed.
