### ISSUE TITLE
Going to the wrong pages using links String, Word,Sentence from the section Faker JavaScript

### ISSUE THREAD

**Issue by alekseipiatkovskii** [Awilum/awilum.dev#22]
Description: 
When clicking on links String, Word from the section Faker JavaScript there is a transition to the page https://github.com/faker-javascript/integer.  At the same time  https://github.com/faker-javascript/string and https://github.com/faker-javascript/word the pages exists.
When clicking on a link https://github.com/faker-javascript/sentece the page opens with an error 404. Mistake in word sentece.
https://github.com/faker-javascript/sentence is working

Environment:
HP Laptop 15s-eq1314ur,Windows 10 Version 22H2 Build 19045.2364 Тип х64
Chrome. Version 108.0.5359.125 (Official build), (64 bit)

Steps to reproduce:
1.Open the page https://awilum.github.io/projects/
2. Scroll down to the section Faker JavaScript
3. Click on link String
4 .Open the page  https://awilum.github.io/projects/
5. Scroll down to the section Faker JavaScript
6. Click on link Word
7. Open the page  https://awilum.github.io/projects/
8. Scroll down to the section Faker JavaScript
9. Click on link Sentence

Actual result:
After the third and sixth steps open https://github.com/faker-javascript/integer
After the the ninth step open https://github.com/faker-javascript/**sentece** with an error 404.

Expected result:
After the third step open https://github.com/faker-javascript/string
After the sixth step open https://github.com/faker-javascript/word
After the the ninth step open https://github.com/faker-javascript/**sentence)**

Attachment:
![Снимок экрана (406)](https://user-images.githubusercontent.com/118691133/210567811-cd59b239-74ac-44ca-aa15-debb4cb18c1d.png)
![Снимок экрана (405)](https://user-images.githubusercontent.com/118691133/210567816-df6d9396-3036-40c3-a244-7e549c703e40.png)
![Снимок экрана (404)](https://user-images.githubusercontent.com/118691133/210567821-ca1df199-ba92-4247-b0e6-64176ee64599.png)
![Снимок экрана (407)](https://user-images.githubusercontent.com/118691133/210570563-88110f86-8209-4dae-9bb1-88f500c90552.png)

https://user-images.githubusercontent.com/118691133/210568571-1f4ad5c3-03b8-471e-94d0-555984954a14.mp4

**Comment by Awilum** [comment]
Issue fixed. Updates on Live.

@alekseipiatkovskii  please retest

**Comment by alekseipiatkovskii** [comment]
Retest is done, the issue is fixed.
