### ISSUE TITLE
404 File not found clicking on the link "sharing" in the list on the page "View" of the project "Glowy PHP"

### ISSUE THREAD

**Issue by rnastasya** [Awilum/awilum.dev#25]
Description:
404 File not found clicking on the link "sharing" in the list on the page "View" of the project "Glowy PHP"

Environment: оpera v. 93.0.4585.37

Steps to reproduce:
1. Open section "Projects" on https://awilum.github.io
2. In project "Glowy PHP" click on the the link "View" 
3. In the list of features click on the link "sharing" in point "Data sharing across views."

Actual result:
Page https://awilum.github.io/glowyphp/view/%7B%7B%20url()%20%7D%7D/glowyphp/view/methods/share/ is opened with error 404 File not found

Expected result:
Page with information about data sharing across views is opened 

Attachment:
![404File not found clicking on the link sharing](https://user-images.githubusercontent.com/71014024/210634897-208264e9-cf02-41b7-b63a-3428934446d3.gif)

**Comment by Awilum** [comment]
Issue fixed. Updates on Live.

@rnastasya  please retest

**Comment by rnastasya** [comment]
@Awilum 
Made retest, issue fixed
