### ISSUE TITLE
External link  WordPress Plugins open in the current tab

### ISSUE THREAD

**Issue by alekseipiatkovskii** [Awilum/awilum.dev#26]
Description:
On the page https://awilum.github.io/projects/ when clicking on the external link [WordPress Plugins](https://wordpress.org/), the page open on the current tab 

Environment:
HP Laptop 15s-eq1314ur,Windows 10 Version 22H2 Build 19045.2364 Тип х64
Google Chrome. Version 108.0.5359.125 (Official build), (64 bit)

Steps to reproduce:
1. Open page https://awilum.github.io/projects/
2. Scroll down to the section WordPress Plugins
3. Click on link WordPress Plugins

Actual result:
The page open in a current tab

Expected result:
The page opens in a new tab

Attachment:

https://user-images.githubusercontent.com/118691133/210794856-390a6125-f3e2-44e9-aee6-dda6825f8b5a.mp4

**Comment by Awilum** [comment]
Issue fixed. Updates on Live.

@alekseipiatkovskii please retest

**Comment by alekseipiatkovskii** [comment]
Retest is done, the issue is fixed.
