### ISSUE TITLE
The page doesn't rederected by link "extends and inheritance" in the list on the page "View" of the project "Glowy PHP"

### ISSUE THREAD

**Issue by rnastasya** [Awilum/awilum.dev#27]
Description: The page doesn't rederected by link "extends and inheritance" in the list on the page "View" of the project "Glowy PHP"

Environment: оpera v. 93.0.4585.37

Steps to reproduce:
1.Open section "Projects" on https://awilum.github.io
2.Click on the the link "View" in project "Glowy PHP" 
3.Click on the link "extends and inheritance" in point "Increase code reuse with view extends and inheritance." in the list of features

Actual result:
Page doesn't change. Linked section #extends-and-ingeritance for rederection doesn't exist. 
Path has changed from https://awilum.github.io/glowyphp/view to https://awilum.github.io/glowyphp/view/#extends-and-ingeritance

Expected result:
Link extends and inheritance redirect to page: https://awilum.github.io/glowyphp/view/methods/extends/

Attachment:
![Linked section #extends-and-ingeritance doesn't exist](https://user-images.githubusercontent.com/71014024/210820166-535d51ba-29e0-42ff-ac79-d3bc4c615343.gif)

**Comment by Awilum** [comment]
Issue fixed. Updates on Live.

Expected result:
link **extends and inheritance** redirect to page: https://awilum.github.io/glowyphp/view/methods/extends/

@rnastasya   please retest

**Comment by rnastasya** [comment]
@Awilum 
Made retest, issue fixed
