### ISSUE TITLE
External links HTML Minifier, Api Explorer in the section WordPress Plugins opens in the current tab

### ISSUE THREAD

**Issue by alekseipiatkovskii** [Awilum/awilum.dev#28]
Description:
On the page https://awilum.github.io/projects/ in the section WordPress Plugins when clicking on the external links HTML Minifier and Api Explorer the pages open on the current tab

Environment:
HP Laptop 15s-eq1314ur,Windows 10 Version 22H2 Build 19045.2364 Тип х64
Google Chrome. Version 108.0.5359.125 (Official build), (64 bit)

Steps to reproduce:
1. Open page https://awilum.github.io/projects/
2. Scroll down to the section WordPress Plugins
3. Click on link [HTML Minifier](https://github.com/Awilum/wp-html-minifier)
4. Open page https://awilum.github.io/projects/
5. Scroll down to the section WordPress Plugins
6. Click on link [Api Explorer](https://github.com/Awilum/wp-api-explorer)

Actual result:
After the third and sixth steps pages open in a current tab

Expected result:
After the third and sixth steps pages open in a new tab

Attachment:

https://user-images.githubusercontent.com/118691133/210954030-9f818bdd-2c69-4b32-a44f-1e5e939b5690.mp4

**Comment by Awilum** [comment]
Issue fixed. Updates on Live.

@alekseipiatkovskii please retest

**Comment by alekseipiatkovskii** [comment]
Retest is done, the issue is fixed.
