### ISSUE TITLE
Going to the wrong page using link Nice from the section Craft CMS Plugins

### ISSUE THREAD

**Issue by alekseipiatkovskii** [Awilum/awilum.dev#29]
Description:
When clicking on link Nice from the section Craft CMS Plugins there is a transition to the page https://github.com/Awilum/craft-benchmark. You get to the same page when you click on the link [Benchmark](https://github.com/craft-plugins/benchmark) from the section Craft CMS Plugins 

Environment:
HP Laptop 15s-eq1314ur,Windows 10 Version 22H2 Build 19045.2364 Тип х64
Chrome. Version 108.0.5359.125 (Official build), (64 bit)

Steps to reproduce:
1.Open the page https://awilum.github.io/projects/
2. Scroll down to the section Craft CMS Plugins
3. Click on link [Nice](https://github.com/craft-plugins/benchmark)

Actual result:
Open https://github.com/Awilum/craft-benchmark

Expected result:
Open the page with "nice" in URI

Attachment:

https://user-images.githubusercontent.com/118691133/210962788-c3eed19b-1979-4f2e-9b41-151febee0dfa.mp4

**Comment by Awilum** [comment]
Issue fixed. Updates on Live.

@alekseipiatkovskii please retest

**Comment by alekseipiatkovskii** [comment]
Retest is done, the issue is fixed.
