### ISSUE TITLE
404 File not found clicking on the link "Elements" in the feature "Component system" of the project "Thermage"

### ISSUE THREAD

**Issue by rnastasya** [Awilum/awilum.dev#30]
Description:
404 File not found clicking on the link "Elements" in the feature "Component system" of the project "Thermage"

Environment: оpera v. 93.0.4585.37

Steps to reproduce:
1. Open section "Projects" on https://awilum.github.io/
2. Click on the link "Thermage" in project "Thermage"
3. In the list of features click on the link "Elements" in the point "Component system"

Actual result:
Page https://awilum.github.io/documentation/elements is opened with error 404 File not found

Expected result:
Page with information about elements is opened

Attachment:
![404 File not found clicking on the link Elements](https://user-images.githubusercontent.com/71014024/211022919-d8db3dbc-d4b0-4644-ae4c-3cddf87346e8.gif)

**Comment by Awilum** [comment]
Issue fixed. Updates on Live.

@rnastasya please retest

**Comment by rnastasya** [comment]
@Awilum
Made retest, issue fixed
