### ISSUE TITLE
404 File not found clicking on the link "Shortcodes API" in the feature "Shortcodes" of the project "Thermage"

### ISSUE THREAD

**Issue by rnastasya** [Awilum/awilum.dev#31]
Description: 404 File not found clicking on the link "Shortcodes API" in the feature "Shortcodes" of the project "Thermage"

Environment: оpera v. 93.0.4585.37

Steps to reproduce:
1. Open section "Projects" on https://awilum.github.io/
2. Click on the link "Thermage" in project "Thermage"
3. In the list of features click on the link "Shortcodes API" in the point "Shortcodes"

Actual result:
Page https://awilum.github.io/documentation/parsers/shortcodes is opened with error 404 File not found

Expected result:
link Shortcodes API redirect to page: https://awilum.github.io/thermage/documentation/parsers/shortcodes/

Attachment:
![404 File not found clicking on the link Shortcodes API](https://user-images.githubusercontent.com/71014024/211024205-29277c41-99de-4246-97f8-cfbef00283b7.gif)

**Comment by Awilum** [comment]
Issue fixed. Updates on Live.

Expected result:
link **Shortcodes API** redirect to page: https://awilum.github.io/thermage/documentation/parsers/shortcodes/

@rnastasya please retest

**Comment by rnastasya** [comment]
@Awilum
Made retest, issue fixed
