### ISSUE TITLE
Internal Server Error: the image isn't displayed on main page

### ISSUE THREAD

**Issue by rnastasya** [Awilum/awilum.dev#32]
Description: Internal Server Error: the image isn't displayed on main page

Environment: оpera v. 93.0.4585.37
                      
Steps to reproduce:
1. Open section "Awilum" on  https://awilum.github.io/
2. Scroll to the section "Opensource contriburions"

Actual result:
The image isn't displayed. Internal Server Error

Expected result:
The image is displayed 

Attachment:
![Image isn't displayed on main page](https://user-images.githubusercontent.com/71014024/211160308-37654dc2-68f9-4b41-9f56-109d225b8e46.gif)

**Comment by Awilum** [comment]
Seems this was an issue related to the service ghchart.rshah.org and it was temporarily down. 

Now it seems to be working.

@rnastasya please retest

**Comment by rnastasya** [comment]
Yes, now image appears.
![it_works](https://user-images.githubusercontent.com/71014024/211417528-29cb2ccc-040b-45dc-8282-ebff2a13a706.jpg)
