### ISSUE TITLE
DNS Probe Finished Nxdomain on the link "and more ..." in the feature "Component system" of the project "Thermage"

### ISSUE THREAD

**Issue by rnastasya** [Awilum/awilum.dev#33]
Description: DNS Probe Finished Nxdomain on the link " and more ..." in the feature "Component system" of the project "Thermage"

Environment: desktop - оpera v. 93.0.4585.37, 
                       mobile - chrome 108.0.5359.128

Steps to reproduce:
1. Open section "Projects" on https://awilum.github.io/
2. Click on the link "Thermage" in project "Thermage"
3. In the list of features click on the link "and more ..." in the point "Component system"

Actual result:
The page https://awilum.github.io/documentation/elements is opened with error 404 File not found
*After finding this error was restarted router and computer, restarted DNS client service, changed  DNS Server. The page is opened with error 

Expected result:
The page with elements is opened

Attachment:
![Desktop DNS Probe Finished Nxdomain on the link and more](https://user-images.githubusercontent.com/71014024/211150859-03f31516-f462-4fad-bd22-960aa8673535.gif)
![mobile DNS_PROBE_FINISHED_NXDOMAIN](https://user-images.githubusercontent.com/71014024/211151107-337aee8c-d972-41f5-927d-53d14bd9d629.jpg)

**Comment by Awilum** [comment]
Issue fixed. Updates on Live.

@rnastasya please retest

**Comment by rnastasya** [comment]
@Awilum
Made retest, issue fixed
