### ISSUE TITLE
404 File not found clicking on the link "MAMP" in the "Flextype" documentation point "Requirements"

### ISSUE THREAD

**Issue by rnastasya** [Awilum/awilum.dev#35]
Description: 404 File not found clicking on the link "MAMP" in the "Thermage" documentation point "Requirements"

Environment: оpera v. 93.0.4585.37

Steps to reproduce:
1. Open section "Projects" on https://awilum.github.io/
2. Click on the link "Flextype" in project "Flextype"
3. Click on the link "Documentation" in the project menu
4. Open point "Requirements" in the section "Getting Started"
5. Click on the link "MAMP" in the point "Shortcodes"

Actual result:
Page https://www.mamp.info/mamp/mac/ is opened with error 404 File not found

Expected result:
Page with information about MAMP is opened

Attachment:
![404_link_MAMP](https://user-images.githubusercontent.com/71014024/211220108-94ba4b97-ae63-4096-821b-1bd79149239c.gif)

**Comment by Awilum** [comment]
@rnastasya please update title and description on of current issue. 

**Requirements** pages is related to **Flextype** project, not for **Thermage** 

I can't reproduce this issue:
<img width="1273" alt="Screenshot 2023-01-09 at 18 23 14" src="https://user-images.githubusercontent.com/477114/211287201-ac5a5692-9af3-4903-be5c-7dcab0648e6b.png">

Seems its was issue on https://www.mamp.info/ side, and they have add redirect to https://www.mamp.info/en/mac/

anyway I will push updated link to new page: https://www.mamp.info/en/mac/

**Comment by Awilum** [comment]
Updates on Live.

@rnastasya please retest

**Comment by rnastasya** [comment]
@Awilum sorry, changed the data 
Made retest, issue fixed
