### ISSUE TITLE
Opening links in a new tab

### ISSUE THREAD

**Issue by alekseipiatkovskii** [Awilum/awilum.dev#4]
Improvement. 

Description:
On the main page when clicking on the links, the page opens instead of the initial page 

Environment:
HP Laptop 15s-eq1314ur,Windows 10 Версия 22H2 Сборка 19045.2364 Тип х64
Chrome. Google Chrome 108.0.0.0 (WebKit 537.36)

Steps to reproduce:
1. Open page https://awilum.github.io/
2. Click on any link

Actual result:
The page opens instead of the initial page

Expected Result:
The page opens in a new tab

Assetsbug:

**Comment by pas050477** [comment]
Also by any links, not only in header

**Comment by Awilum** [comment]
Internal links should open in the current tab; external links should open in a new tab.
If you are talking about internal links - it's not an issue.

**Comment by alekseipiatkovskii** [comment]
ок
