### ISSUE TITLE
The page with the site map does not open

### ISSUE THREAD

**Issue by alekseipiatkovskii** [Awilum/awilum.dev#5]
Description: 
On the main page in the footer section by clicking on the link “SITEMAP”, sitemap page isnt opened 

Environment:
HP Laptop 15s-eq1314ur,Windows 10 Версия 22H2 Сборка 19045.2364 Тип х64
Chrome. Google Chrome 108.0.0.0 (WebKit 537.36)

Steps to reproduce:
1. Open page https://awilum.github.io/
2. Scroll down to the footer section
3. Click on the link “SITEMAP”

Actual result: 
 Sitemap page isnt opened 
 
Expected Result: 
 Sitemap page is opened

 Assetsbug:
Attached screenshots
![Снимок экрана (364)](https://user-images.githubusercontent.com/118691133/209462944-f699165f-d3b2-486a-b01f-3252f2b6ff84.png)
![Снимок экрана (363)](https://user-images.githubusercontent.com/118691133/209462947-24c8c475-6cd6-4353-b50d-afdfa07d7414.png)

**Comment by Awilum** [comment]
Issue fixed. Updates on Live.

@alekseipiatkovskii please retest

**Comment by alekseipiatkovskii** [comment]
Retest is done, the issue is fixed.
