### ISSUE TITLE
Projects tab is not highlighted on the cheatsheets page Header

### ISSUE THREAD

**Issue by meowlder** [Awilum/awilum.dev#6]
Projects tab is not highlighted on the cheatsheets page Header

Environment: Chrome 108.0.5359.98, 1920x1080; MacOS 12.6 

Steps to reproduce:
1. Open the page https://awilum.github.io/cheatsheets/
2. Clik on the Linux image
3. Go back to Cheatsheets
4. Click on the Master CSS image

Actual result:
Projects tab is not highlighted in the page header

Expected result:
The current tab should be highlighted

Attachment:

https://user-images.githubusercontent.com/121216123/210083576-ef031a8e-2b06-49cc-b690-c0ea7b440c7f.mov

**Comment by Awilum** [comment]
Issue fixed. Updates on Live.

@vetamalder please retest

**Comment by meowlder** [comment]
Retest is done, the issue is fixed.
