### ISSUE TITLE
The Linux logo does not change its size while resizing the page

### ISSUE THREAD

**Issue by meowlder** [Awilum/awilum.dev#7]
Description: 
The Linux logo does not change its size while resizing the page

Environment: Chrome 108.0.5359.98; MacOS 12.6 

Steps to reproduce:
1. Open the page https://awilum.github.io/cheatsheets/ 
2. Narrow the browser window by dragging the left border to the left and then drag it back to the right 

Actual result:
The Linux logo stays static when the window is being resized

Expected result:
The Linux logo should adapt to the screen resolution and be centered within the border 

Attachment: 

https://user-images.githubusercontent.com/121216123/210085715-5120a052-7f34-4c78-bc44-3055cf5d4150.mov

**Comment by Awilum** [comment]
Issue fixed. Updates on Live.

@vetamalder please retest

**Comment by meowlder** [comment]
Retest is done, the issue is fixed.
